import React from 'react';

interface RepositorySummaryProps {
    summary: string;
}

export default function RepositorySummary({ summary }: RepositorySummaryProps) {
    return (
        <div className="bg-surface-card border border-hairline rounded-lg p-7 font-sans relative overflow-hidden">
            {/* Sparkle badge */}
            <div className="absolute top-0 right-0 w-24 h-24 bg-primary/5 rounded-bl-full flex items-start justify-end p-4 text-primary">
                <span className="text-xl">✨</span>
            </div>

            <div className="max-w-2xl">
                <h4 className="text-base font-serif font-medium text-ink mb-3.5 flex items-center gap-2">
                    AI Repository Insights
                </h4>
                <p className="text-sm text-body-strong leading-relaxed font-serif italic text-justify pr-6">
                    "{summary}"
                </p>
                
                <div className="mt-5 pt-3.5 border-t border-hairline flex items-center gap-2 text-[10px] text-muted font-semibold uppercase tracking-wider">
                    <span>Generated by CodeBERT Engine</span>
                    <span>&bull;</span>
                    <span>Aggregate Analysis Complete</span>
                </div>
            </div>
        </div>
    );
}
